#!/bin/sh

# KEYWORD: firstboot
# PROVIDE: frieze_fetchkey
# REQUIRE: NETWORKING
# BEFORE: LOGIN

# Define frieze_fetchkey_enable=YES in /etc/rc.conf to enable SSH key fetching
# when the system first boots.
: ${frieze_fetchkey_enable=NO}

# Set frieze_fetchkey_user to change the user for which SSH keys are provided.
: ${frieze_fetchkey_user=frieze-user}

. /etc/rc.subr

name="frieze_fetchkey"
rcvar=frieze_fetchkey_enable
start_cmd="frieze_fetchkey_run"
stop_cmd=":"

SSHKEYURL="http://169.254.169.254/v1/public-keys"
SSHKEYFILE="/usr/local/etc/ssh/ca.pub"

frieze_fetchkey_run()
{
        # Grab the provided SSH public key and add it to the
        # right authorized_keys file to allow it to be used to
        # log in as the specified user.
        echo "Fetching SSH public key for ${frieze_fetchkey_user}"
        mkdir -p `dirname ${SSHKEYFILE}`
        fetch -o - ${SSHKEYURL} | awk -F ' ' '{print $1, $2}' > ${SSHKEYFILE}
        if [ -f ${SSHKEYFILE} ]; then
                chmod 0644 ${SSHKEYFILE}
        else
                echo "Fetching SSH public key failed!"
        fi
}

load_rc_config $name
run_rc_command "$1"
