---
# storage tasks
- name: initialize disks with gpt
  action: command gpart create -s gpt {{ item.1.dev }}
  with_subelements:
    - "{{ archw[inventory_hostname].storage_pools }}"
    - disks
  ignore_errors: True
- name: add zfs partition
  action: command gpart add -t freebsd-zfs -l {{ item.1.label }} -b 1M -s {{ item.1.size }} {{ item.1.dev }}
  with_subelements: 
    - "{{ archw[inventory_hostname].storage_pools }}"
    - disks
  ignore_errors: True
- name: create zpool
  action: command zpool create {{ item.name }} {{ item.redundancy }} {{ item.disks | join(' ', attribute='fqlabel') }}
  with_items: 
    - "{{ archw[inventory_hostname].storage_pools }}"
  ignore_errors: True